---
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Reed RStudio server

There are a couple of advantages to using R on the Reed RStudio Server:

-   Accessible from any computer with an internet connection
-   No need to install software
-   Provides some storage for files, data, and images
-   Useful for collaborative work (caution: see notes below)

To access the server, head to [rstudio.reed.edu](https://rstudio.reed.edu) and log in using your Kerberos credentials.

#### Installing libraries

Most of the libraries that you will need are already installed on the server. If you want to use a package that is not already on the server you can type `install.package("packagename")` in the console; this will install a library within your own user space on the server. If you run into errors installing or using packages, contact the RStudio server administrators at [rstudio-support\@reed.edu](mailto:rstudio-support@reed.edu).

#### Uploading data to the Reed Rstudio server

You might have some data on your computer that you would like to work with on the server. To upload data from your computer:

-   log in to the [RStudio server](https://rstudio.reed.edu) to open an RStudio session

-   in the bottom right corner of your screen, locate the "Files" pane

-   If you are working in a new session, then most likely your location within the "Files" pane will be automatically set to your "Home" directory

    -   If you are in your "Home" directory, you should see a house icon in the top left of the "Files" pane, with *only* the word "Home" next to it. If there are other things listed next to "Home", click on the house icon to be redirected to your "Home" directory.

-   navigate to the folder (on the server, within the "Files" pane) where you want to store your data

    -   to create a new folder, select "New Folder" from the left side of the "Files" pane toolbar.

-   click the "Upload" button (with a yellow, up-facing arrow beside it)

-   choose the file on your computer and click "Open"

The data is now uploaded to the server. To use your data, you will need to import your file into your R environment from the location where you saved it on the server. For instructions on importing a `.csv` into your R environment, see the ['From a .csv' page](https://www.reed.edu/data-at-reed/resources/R/from-a-.csv.html). For more information on this topic, as well as specific instructions for loading different types of data, see the pages under the 'Loading Data' section of the [R tutorials page](https://www.reed.edu/data-at-reed/resources/R/index.html).

#### Jointly editing documents

One of the advantages to working on RStudio server is the ability to easily share projects with collaborators. When working on shared projects, it is best to have **one** active editor for a project, because RStudio Server does not have the simultaneous editing ability that a tool like Google Docs does. If the server detects that multiple editors are accessing the file, it will temporarily block further editing of that file and may not save your work. If the server gives you a saving error, copy and paste your code into a text editor or Google Doc to retain your work. You can then close the file on the Rstudio server, wait for your partner to be done with their edits, and then reopen the file to implement your changes (copy/paste the text you had saved).

If you want to jointly edit documents with collaborators, you can look into using [Git and GitHub](https://happygitwithr.com/rstudio-git-github.html).

#### Help! The server is broken / down / having problems

Every five minutes, the RStudio Server checks to make sure it is running smoothly; if there is a glitch, the server will restart. This restart should solve any server-level problems.

#### Error occurred during transmission (broken sessions)

At some point, you may encounter an error when you log in: RStudio initialization error, 'Error occurred during transmission'. Sometimes RStudio user sessions encounter errors of some stripe; while this might be annoying, it is also a problem you can solve. To exit a misbehaving session or create a new session, visit <https://rstudio.reed.edu/home>.
