---
output: html_document
---

# R Markdown

R Markdown is a document type that lets you mix plain writing and code to produce reports, assignments, and presentations using R. It’s most useful when you want to integrate R output (like plots or tables) with commentary. You can open a blank R Markdown file under File / New File / R Markdown, and then adjust any settings you want.

#### YAML and output

At the top of any R Markdown document is the YAML header. This section denotes general settings/metadata for the document, including

* Title/Date/Author
* Output method (html, pdf, .doc, GitHub file, etc.)
* LaTeX packages included
* Table of contents (y/n, settings)

The only one of these that you absolutely need is the output method. When you knit an R Markdown file to produce a clean output, R needs to know what type of file you want it to push out.

#### Code
You can put R code into an R Markdown document, and the evaluated code results will appear in the output document.

The "Insert" button at the top of the editor window will insertt a blank code chunk for you, or you can define it manually with the three backticks at top and bottom as in the picture above. Every chunk runs one after the other, so any objects that you create in an earlier chunk will be available for you to use in a later chunk. A completely new R session is created when you run an Rmd file, however, so anything that you don’t explicitly access in the document won’t be available, and calling on it will throw an error.

#### Text formatting

In between code chunks, you can type plain text to put in the output document. The formatting style that R Markdown uses is a method called Markdown, which gives some basic text-editing features such as

* Bold/italics/underline
* Bulleted/numbered lists
* Links
* Headers
* Equation formatting through LaTeX

For info on all of these formatting methods, try this [cheatsheet](https://rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf) on Markdown syntax.

Check out this book chapter for more help with R Markdown.